# adct - CI Build
# https://github.com/ArtiomL/adct
# Artiom Lichtenstein
# v1.0.1, 29/11/2017

sudo: required

services:
  - docker

before_install:
  - docker pull artioml/adct
  - docker run -dit -p 80-81:80-81 -p 443:443 artioml/adct
  - docker ps -a

install:
  - sudo apt-get install -y curl

script:
  - curl -k https://127.0.0.1:443/uri13/secure/index.php -u user:user
